on: [push, pull_request, workflow_dispatch]

jobs:
  build_job:
    runs-on: ubuntu-18.04
    name: Build for ${{ matrix.arch }} (${{ matrix.arch }} host)

    strategy:
      matrix:
        include:
          - arch: armv7
            distro: ubuntu18.04
          #- arch: armv6
          #  distro: ubuntu18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: uraimo/run-on-arch-action@v2
        name: Building ${{ matrix.arch }}
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          githubToken: ${{ github.token }}

          setup: |
            mkdir -p "${PWD}/build"

          dockerRunArgs: |
            --volume "${PWD}:/build"

          env: | # YAML, but pipe character is necessary
            artifact_name: stalwart-${{ matrix.arch }}

          shell: /bin/bash

          install: |
            apt-get update -y
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh
            ./llvm.sh 14 all
            apt-get install -yq curl wget 
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

          # Produce a binary artifact and place it in the mounted volume
          run: |
            cd /build
            cargo build --release

      - name: Show the artifact
        # Items placed in /artifacts in the container will be in
        # ${PWD}/artifacts on the host.
        run: |
          ls -al "${PWD}/target/*"
