#on: [push, pull_request, workflow_dispatch]

jobs:
  build_job:
    runs-on: ubuntu-18.04
    name: Build for ${{ matrix.arch }} (${{ matrix.arch }} host)

    strategy:
      matrix:
        include:
          - arch: armv7
            distro: ubuntu18.04
          #- arch: armv6
          #  distro: ubuntu18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: uraimo/run-on-arch-action@v2
        name: Building ${{ matrix.arch }}
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          githubToken: ${{ github.token }}

          setup: |
            mkdir -p "${PWD}/build"

          dockerRunArgs: |
            --volume "${PWD}:/build"

          env: | # YAML, but pipe character is necessary
            artifact_name: stalwart-${{ matrix.arch }}

          shell: /bin/bash

          install: |
            apt-get update -y
            apt-get install -yq build-essential curl clang llvm lsb-release software-properties-common gnupg 
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh
            sed -i 's#/proc/self/exe#$(which head)#g' rustup-init.sh
            sed -i 's#/proc/cpuinfo#/proc/cpuinfo 2> /dev/null || echo ''#g' rustup-init.sh
            sed -i 's#get_architecture || return 1#RETVAL=$(gcc -dumpmachine | sed "s/-/-unknown-/") #g' rustup-init.sh
            sh -x rustup-init.sh -y --default-host=$(gcc -dumpmachine | sed 's/-/-unknown-/')
            rm rustup-init.sh

          # Produce a binary artifact and place it in the mounted volume
          run: |
            source "$HOME/.cargo/env"
            cd /build
            cargo build --release

      - name: Show the artifact
        # Items placed in /artifacts in the container will be in
        # ${PWD}/artifacts on the host.
        run: |
          ls -al "${PWD}/target/*"
